-- Migration number: 0002 	 2026-09-05T20:26:08.976Z
--
-- Core product schema: users, trips, trip_members, trip_cities,
-- itinerary_items, todos. See docs/foundation.md (Entities) for the model.
--
-- Conventions:
-- * Primary keys are TEXT ids generated by app code (crypto.randomUUID()).
-- * Every mutable row carries created_at/updated_at (ISO 8601 UTC text),
--   set by app code; updated_at drives the sync/polling layer later.
-- * Times on content rows are local wall-clock text (ISO 8601, no offset)
--   plus an IANA zone per end; *_utc columns are derived instants computed
--   by app code on write, used only for ordering.
-- * Dates are ISO 8601 date text (YYYY-MM-DD).
-- * Trip-scoped tables cascade on trip deletion; user-side references never
--   cascade (there is no account-deletion flow in v1).

-- Account per person, keyed by external identity provider. A user exists
-- independently of any trip.
CREATE TABLE users (
  id TEXT PRIMARY KEY,
  auth_provider TEXT NOT NULL,
  auth_subject TEXT NOT NULL,
  email TEXT,
  display_name TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (auth_provider, auth_subject)
);

-- A trip. Dates are derived from its cities, so there are no date columns;
-- there is deliberately no status/phase column (foundation.md: trip lifecycle
-- is a client-side presentation concern, never server state).
CREATE TABLE trips (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  created_by TEXT NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Membership: who is on a trip. Every member can edit everything (no role
-- column; creator-only trip deletion derives from trips.created_by). The
-- optional arrival/departure dates are the member's personal presence window
-- when it differs from the trip's span.
CREATE TABLE trip_members (
  trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id),
  arrival_date TEXT,
  departure_date TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (trip_id, user_id)
);

-- Ordered cities within a trip. timezone is the city's IANA zone, used to
-- resolve wall-clock times for items in that city. Dates are nullable:
-- an undated city is a real planning state.
CREATE TABLE trip_cities (
  id TEXT PRIMARY KEY,
  trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  timezone TEXT NOT NULL,
  arrival_date TEXT,
  departure_date TEXT,
  position INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Schedule content. city_id is nullable because flights span cities (and a
-- deleted city must not delete its items — SET NULL). A stay is one row
-- holding check-in (start) and checkout (end); clients project it into two
-- schedule entries. All time columns are nullable: untimed/undated items are
-- a real planning state. Per-end zones exist for flights (depart in the
-- origin's zone, arrive in the destination's). position orders untimed items
-- manually. links is a JSON array of URLs (display-only).
CREATE TABLE itinerary_items (
  id TEXT PRIMARY KEY,
  trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  city_id TEXT REFERENCES trip_cities(id) ON DELETE SET NULL,
  kind TEXT NOT NULL CHECK (kind IN ('flight', 'stay', 'reservation', 'activity')),
  title TEXT NOT NULL,
  notes TEXT,
  address TEXT,
  confirmation_number TEXT,
  links TEXT,
  start_local TEXT,
  start_tz TEXT,
  end_local TEXT,
  end_tz TEXT,
  start_utc TEXT,
  end_utc TEXT,
  departure_airport TEXT,
  arrival_airport TEXT,
  position INTEGER,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Per-trip to-dos. Assignee is optional; done is 0/1. Due times use the same
-- local + zone model as itinerary items (no derived UTC: to-dos are not
-- ordered on a timeline). Apple Reminders sync mapping lives client-side,
-- not here (Reminders IDs are per-device/per-account).
CREATE TABLE todos (
  id TEXT PRIMARY KEY,
  trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  done INTEGER NOT NULL DEFAULT 0,
  due_local TEXT,
  due_tz TEXT,
  assignee_user_id TEXT REFERENCES users(id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Indexes for the obvious access paths (everything else is by-trip via FKs
-- that SQLite already needs indexed on the child side for cascades).
CREATE INDEX idx_trip_members_user ON trip_members(user_id);
CREATE INDEX idx_trip_cities_trip_position ON trip_cities(trip_id, position);
CREATE INDEX idx_itinerary_items_trip_start ON itinerary_items(trip_id, start_utc);
CREATE INDEX idx_todos_trip ON todos(trip_id);

UPDATE meta SET value = '2' WHERE key = 'schema_version';
